output_dir: scratch/experiments/

dataset:
  class: IndFB15K
  root: datasets/knowledge_graphs/
  version: FG

model:
  class: NBFNet
  input_dim: 32
  hidden_dims: [32, 32, 32, 32, 32, 32]
  message_func: distmult
  aggregate_func: pna
  short_cut: yes
  layer_norm: yes
  dependent: yes
  remove_one_hop: yes

task:
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 0.5
  metric: [mr, mrr, hits@1, hits@3, hits@10, hits@10_50]

optimizer:
  class: Adam
  lr: 5.0e-3

train:
  gpus: null
  batch_size: 64
  num_epoch: 2
  log_interval: 100